name: dartDemoRoadtok8s
description: An absolute bare-bones web app.
version: 1.0.0
homepage: https://dart.demo.roadtok8s.com
publish_to: none

# environment:
#   sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.7.0

# dev_dependencies:
#   build_runner: ^2.1.4
#   build_web_compilers: ^3.2.1
#   lints: ^2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  build_runner: 
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  test_process: ^2.0.0
